version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
      - redis
    volumes:
      - .:/code
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
  worker_1:
    build:
      context: .
    hostname: worker_1
    entrypoint: celery
    command: -A tasks worker --loglevel=info 
    volumes:
      - .:/code
    links:
      - rabbit
    depends_on:
      - rabbit
